repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      # - id: check-yaml # does not work well with helm chart
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer

  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.1"
    hooks:
      - id: poetry-check
        args: ["--lock"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.10"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        pass_filenames: false
        additional_dependencies: [
            fastapi,
            types-requests,
            types-pyyaml,
            pydantic,
          ] # pytest,
        args: [--config-file=./pyproject.toml, .]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

