[project]
name = "anonymize-me"
version = "0.1.0"
description = "Streamlit application for anonymizing PI/PII data in email content and attachments."
authors = [{ name = "Anonymize Me" }]
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "openai>=1.0.0",
    "pypdf>=3.16.2",
    "reportlab>=4.0.7",
    "python-docx>=1.1.0"
]

[tool.uv]
package = true
